### PR TITLE
Added fyrcon-right-*, a way to display fycons :after content.

### PR DESCRIPTION
**Pull request by Joao-S-Martins**
This is something that I've had to hack for in ModQ that I would prefer already exist in livefyre-bootstrap, for future maintainability and code reuse.

### CODE REVIEW

**Comment by Joao-S-Martins** [comment]
#review @philcho

**Comment by philcho** [comment]
#feedback @Joao-S-Martins

My understanding is that fycon classes weren't constructed to be used directly on content containers but, instead, applied to empty inline elements (ex: <i class="fycon-plus"></i>). It's similar to how Bootstrap suggests we use Glypicons: http://getbootstrap.com/components/#glyphicons-how-to-use

Can you give an example of where ModQ is using a fycon after text? Could an empty inline element be used instead?

If not, then maybe combine the classes for efficiency:

.fycon-action-etc:before,
.fycon-right-action-etc:after { 
     content: "\e000";
}

**Comment by Joao-S-Martins** [comment]
@philcho at the least, I think we need to keep some of the functions I added so that I can specify the font and stuff in my own :after without it writing in a :before
Example: https://github.com/Livefyre/lfmod/blob/production/src/less/studio/heading.less#L172

**Comment by philcho** [comment]
@Joao-S-Martins Sounds good.

**Comment by Joao-S-Martins** [comment]
#review @philcho

**Pull request merged**
